server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml  # Persist the positions file

scrape_configs:
  - job_name: 'file-logs'
    static_configs:
      - targets:
          - localhost
        labels:
          job: 'python-app'
          __path__: /data/app.log  # Path to your log file

    pipeline_stages:
      - json:
          expressions:
            level: level
            app_name: app_name