server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push  

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            app_name: app_name  
            timestamp: timestamp
            level: level
            message: message
      - drop:
          # Drop logs where the `app_name` field is missing or empty
          source: app_name
          expression: "^$"  
      - labels:
          app_name: app_name  
          level: level  

      
